import {Args, Command, Flags} from '@oclif/core'
import {existsSync, mkdirSync, readFileSync, writeFileSync} from 'node:fs'
import {homedir} from 'node:os'
import {join} from 'node:path'
import {appendAudit} from '../../audit.js'

interface PendingApproval {
  code: string
  story: string | null
  env: string
  createdAt: string
  expiresAt: string
  approved: boolean
  approvedAt: string | null
}

function pendingPath(): string {
  return join(homedir(), '.agentia-gov-guard', 'pending.json')
}

function loadPending(): PendingApproval[] {
  try {
    if (!existsSync(pendingPath())) return []
    const parsed: unknown = JSON.parse(readFileSync(pendingPath(), 'utf8'))
    return Array.isArray(parsed) ? (parsed as PendingApproval[]) : []
  } catch {
    return []
  }
}

function savePending(records: PendingApproval[]): void {
  mkdirSync(join(homedir(), '.agentia-gov-guard'), {recursive: true})
  writeFileSync(pendingPath(), JSON.stringify(records, null, 2), 'utf8')
}

export default class GovApprove extends Command {
  static description = 'Approve a one time PROD promotion code generated by gov check.'

  static examples = [
    '<%= config.bin %> <%= command.id %> AP-XXXXXX --story US-1234 --env PROD',
  ]

  static args = {
    code: Args.string({description: 'One time approval code from gov check.', required: true}),
  }

  static flags = {
    story: Flags.string({char: 's', description: 'User story ID the code was issued for.'}),
    env: Flags.string({char: 'e', description: 'Target environment the code was issued for.'}),
    json: Flags.boolean({char: 'j', description: 'Machine readable JSON output.', default: false}),
  }

  public async run(): Promise<void> {
    const {args, flags} = await this.parse(GovApprove)
    const code = args.code as string
    const story = flags.story ?? null
    const env = flags.env ?? null
    const asJson = flags.json ?? false

    const records = loadPending()
    const now = Date.now()
    const live = records.filter((r) => Date.parse(r.expiresAt) > now)
    if (live.length !== records.length) savePending(live)

    const match = live.find((r) => r.code === code)
    if (!match) {
      const detail = 'Unknown or already consumed approval code. Run gov check to generate a new one.'
      if (asJson) this.log(JSON.stringify({approved: false, code, detail}, null, 2))
      else this.log(detail)
      this.exit(1)
    }

    if (story && (match as PendingApproval).story !== story) {
      const detail = `Code ${code} was issued for story ${(match as PendingApproval).story ?? 'none'}, not ${story}.`
      if (asJson) this.log(JSON.stringify({approved: false, code, detail}, null, 2))
      else this.log(detail)
      this.exit(1)
    }

    if (env && (match as PendingApproval).env !== env) {
      const detail = `Code ${code} was issued for env ${(match as PendingApproval).env}, not ${env}.`
      if (asJson) this.log(JSON.stringify({approved: false, code, detail}, null, 2))
      else this.log(detail)
      this.exit(1)
    }

    const record = match as PendingApproval
    if (record.approved) {
      const rerun = `agentia gov check --story ${record.story ?? '<id>'} --env ${record.env} --approve-code ${record.code}`
      if (asJson) {
        this.log(JSON.stringify({approved: true, code, alreadyApproved: true, rerun}, null, 2))
      } else {
        this.log(`Code ${code} was already approved. Re-run: ${rerun}`)
      }
      return
    }

    record.approved = true
    record.approvedAt = new Date().toISOString()
    savePending(live)
    appendAudit({event: 'code-approved', code: record.code, story: record.story, env: record.env})

    const rerun = `agentia gov check --story ${record.story ?? '<id>'} --env ${record.env} --approve-code ${record.code}`
    if (asJson) {
      this.log(JSON.stringify({approved: true, code, record, rerun}, null, 2))
    } else {
      this.log(`Approved ${code} for story ${record.story ?? 'none'} to ${record.env}.`)
      this.log(`Re-run: ${rerun}`)
    }
  }
}
